//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Frame()
        {
            this.Actions = new HashSet<Action>();
        }
    
        public System.Guid FrameGUID { get; set; }
        public int ActionID { get; set; }
        public string FrameName { get; set; }
        public string FrameAuthor { get; set; }
        public string FrameAuthorURL { get; set; }
        public bool IsSquare { get; set; }
        public string FrameExtension { get; set; }
        public byte[] FrameBytes { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> AddedByPersonID { get; set; }
        public Nullable<int> FrameByteSize { get; set; }
        public string BackgroundHex { get; set; }
    
        public virtual Action Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Actions { get; set; }
        public virtual Person Person { get; set; }
    }
}
