//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frame
    {
        public int FrameID { get; set; }
        public int ActionID { get; set; }
        public string FrameName { get; set; }
        public string FrameAuthor { get; set; }
        public string FrameAuthorURL { get; set; }
        public bool IsSquare { get; set; }
        public string FrameFilename { get; set; }
    
        public virtual Action Action { get; set; }
    }
}
