//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public System.Guid PhotoGUID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool MakePublic { get; set; }
        public byte[] PhotoBytes { get; set; }
        public Nullable<int> PhotoByteSize { get; set; }
        public Nullable<System.Guid> FrameGUID { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Person Person { get; set; }
    }
}
