//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackedGUIDAccess
    {
        public int TrackedGUIDAccessID { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime Datetime { get; set; }
        public string IP { get; set; }
        public bool CompletedAction { get; set; }
    
        public virtual TrackedGUID TrackedGUID { get; set; }
    }
}
