//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackedGUID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackedGUID()
        {
            this.TrackedGUIDAccesses = new HashSet<TrackedGUIDAccess>();
        }
    
        public System.Guid GUID { get; set; }
        public int PersonID { get; set; }
        public int ActionID { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackedGUIDAccess> TrackedGUIDAccesses { get; set; }
    }
}
